<?php
$urlPage = "?";

if (strlen($this->dispatcher->getParam("txtSearch")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
if(strlen($this->dispatcher->getParam("txtFormDate"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtFormDate" => $this->dispatcher->getParam("txtFormDate")));
}
if(strlen($this->dispatcher->getParam("txtToDate"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtToDate" => $this->dispatcher->getParam("txtToDate")));
}
?>

<div class="page-title">
    <div class="title_left">
        <h3>Promotion</h3>
    </div>
</div>
<?php if (isset($msg_result)) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<?php $message_success = isset($msg_del["success"]) ? $msg_del["success"] : '';
$message_error = isset($msg_del["error"]) ? $msg_del["error"] : '';
if (!empty($message_success)) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $message_success; ?>
    </div>
<?php }
if (!empty($message_error)) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-error alert-dismissible fade in" role="alert">
        <?php echo $message_error; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-promotion" method="post" action="">
    <?php $keyword = $this->dispatcher->getParam("txtSearch");
        $formdate = $this->dispatcher->getParam("txtFormDate");
        $todate = $this->dispatcher->getParam("txtToDate");

    ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2 class="">Keyword</h2>
                        </div>
                        <div class="col-md-2">
                            <input maxlength="255" class="form-control" type="text" name="txtSearch"
                                   placeholder="ID, Code" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <h2>From</h2>
                        <div class="col-md-2">
                            <input autocomplete="off" placeholder="Form Date (Start Date)" value="<?php echo isset($formdate) ? $formdate : ""; ?>" type="text" id="txtFormDate" data-timepicker="true" data-time-format='hh:ii' name="txtFormDate"  class="form-control col-md-7 col-xs-12 datepicker-here">
                        </div>

                        <h2>To</h2>
                        <div class="col-md-2">
                            <input autocomplete="off"  placeholder="To Date (Start Date)" value="<?php echo isset($todate) ? $todate : ""; ?>" type="text" id="txtToDate" data-timepicker="true" data-time-format='hh:ii' name="txtToDate"  class="form-control col-md-7 col-xs-12 datepicker-here">
                        </div>
                        <div class="col-md-2">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                            <a class="btn btn-info" href="<?php echo $this->url->get("/promotion/create"); ?>">Add New</a>
                        </div>

                    </div>
                    <div>
                        <strong>Total</strong>
                        <?php echo $list_promotion->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header">
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input
                                                type="checkbox" id="checkboxAll"><span
                                                class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID</th>
                                <th class="column-title">Code</th>
                                <th class="column-title">Percent %</th>
                                <th width="150px" class="column-title">Start Date</th>
                                <th width="150px" class="column-title">End Date</th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>
                            <?php
                            /**
                             *  @var Indianimmigrationorg\Models\VisaPromotion $item
                             **/
                            ?>
                            <tbody class="tb_body">
                            <?php foreach ($list_promotion->items as $item) { ?>
                                <tr>
                                    <td><label class="container_checkbox"><input class="check" name="item[]"
                                                                                 value="<?php echo $item->getPromotionId() ?>"
                                                                                 type="checkbox"><span
                                                    class="checkmark_checkbox"></span></label></td>
                                    <td class=""><?= $item->getPromotionId() ?></td>
                                    <td class=""><?= $item->getPromotionCode() ?></td>
                                    <td class=""><?= $item->getPromotionPercent() ?></td>
                                    <td class=""><?= $this->my->formatTime($item->getPromotionStartdate()) ?></td>
                                    <td class=" "><?= $this->my->formatTime($item->getPromotionEnddate()) ?></td>


                                    <td><a class="btn btn-primary btn-xs margin-0"
                                           href="<?php echo $this->url->get("/promotion/edit?id=" . $item->getPromotionId()); ?> ">View</a>
                                    </td>
                                </tr>

                            <?php } ?>
                            </tbody>
                        </table>

                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <label for="slcAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction"
                                    style="display: inline-block;width: 40%">
                                <option value="" selected>Please select</option>
                                <option value="drop">Drop</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <?php if ($list_promotion->total_pages > 1) { ?>
                                <nav class="paginate-footer">
                                    <?php if ($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $list_promotion->current, $list_promotion->total_pages, 2);
                                    ?>
                                </nav>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        $('button[name=search]').click(function () {
            $('form[name=form-promotion]').prop('action', '<?php echo $this->url->get('/promotion'); ?>');
            $('form[name=form-promotion]').submit();
        });
        $('.delete-all').click(function () {
            $('form[name=form-promotion]').prop('action', '<?php echo $this->url->get('/promotion/delete'); ?>');
            $('form[name=form-promotion]').submit();
        });
    });
</script>