<script>
    $( document ).ready(function() {
        $('form[name=type-form]').submit(function(event) {
            var valid = true;
            if ($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=submit]').prop('disabled', true);
            }
        });

    });

</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Port Type</h3>
    </div>
</div>
<div class="clearfix"></div>
<?php if(!empty($messages['message']))
{
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage']?>">
        <?php echo $messages['message']; ?>
    </p>
<?php }	?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 class="form_title">Form Edit</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form name="type-form" id="device-form" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <input type="hidden" name="save" id="save" value="<?php echo \Indianimmigrationorg\Models\VisaLanguage::GENERAL ;?>" />
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10" value="<?php echo isset($formData["type_order"]) ? $formData["type_order"] : "" ?>" type="text" id="txtOrder" name="txtOrder"  class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["type_order"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-order"><?php echo isset($messages["type_order"]) ? $messages["type_order"] : "";?></span>
                        </div>
                    </div>                    
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["type_active"]) && $formData["type_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["type_active"]) && $formData["type_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="submit" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="/porttype">Cancel</a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <ul class="nav nav-pills" role="tablist">
                <?php
                foreach ( $formData['arr_language'] as $code => $lang ){
                    $active = $formData['lang_current']== $code?"active":"";
                    ?>
                    <li role="presentation" class="<?php echo $active; ?>">
                        <a href="#<?php echo $code ?>translate"
                           aria-controls="<?php echo $code ?>translate"
                           role="tab"
                           data-toggle="tab"><?php echo $code .' - '. $lang; ?></a>
                    </li>
                <?php } ?>
            </ul>
            <div class="tab-content">
                <?php foreach ($formData['arr_language'] as $code => $lang ) {
                    $active = $formData['lang_current']== $code?"active":"";
                    ?>
                    <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                        <br>
                        <form name="type-form<?php echo $code; ?>" id="type-form<?php echo $code; ?>" action="" data-parsley-validate class="form-horizontal form-label-left" method="post">
                            <input type="hidden" name="save" id="save" value="<?php echo $code; ?>" />
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Name <span
                                            class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["type_name"]) ? $formData['arr_translate'][$code]["type_name"] : "" ?>"
                                           type="text" id="txtName<?php echo $code; ?>" name="txtName"
                                           class="form-control col-md-7 col-xs-12 <?php echo (isset($messages[$code]["type_name"])) ? $messages["status"] : ""; ?>">
                                    <span class="text-danger msg-name-<?php echo $code; ?>"><?php echo isset($messages[$code]["type_name"]) ? $messages[$code]["type_name"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button name="sbmArea<?php echo $code; ?>" type="submit" class="btn btn-success">
                                        <?php echo 'Save (' . $lang.')'; ?>
                                    </button>
                                </div>
                            </div>
                            <script>
                                $(document).ready(function () {                                    
                                    $('form[name=type-form<?php echo $code; ?>]').submit(function (event) {
                                        valid = true;
                                        if ($('#txtName<?php echo $code; ?>').val() == '') {
                                            valid = false;
                                            $('.msg-name-<?php echo $code;?>').text("Name field is required.");
                                            $('#txtName<?php echo $code; ?>').addClass("border-red");
                                        } else {
                                            $('.msg-name-<?php echo $code;?>').text('');
                                            $('#txtName<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if (!valid) event.preventDefault();
                                        if (valid) {
                                            $('#sbmPage<?php echo $code; ?>').prop('disabled', true);
                                        }
                                    });
                                });
                            </script>
                        </form>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
