<div class="padding-block-large pt-50 pb-10 text-center">
    <div class="container"><img class=" lazyload" src="https://dovyy1zxit6rl.cloudfront.net/uploads/sx-1602664268.svg"
                                data-src="https://dovyy1zxit6rl.cloudfront.net/uploads/404-1604482403.png"
                                title="404 Error" alt="404 Error">
        <h2 class="text-28 text-lg-36 mt-20 mt-lg-30">Oops! Page not found</h2>
        <p class="mb-20">Sorry, We can't seem to find the page you're looking for. Error code: 404</p> <a
                href="<?php echo $this->url->get("/"); ?>" class="btn btn-main px-lg-80" target="_self" title="Back to Home">Back to Home</a>
    </div>
</div>
