<?php
use  Indianimmigrationorg\Repositories\User;
use Indianimmigrationorg\Repositories\Order;
use Indianimmigrationorg\Repositories\Country;
$keyword =$this->dispatcher->getParam("txtSearch");
$from_apply = $this->dispatcher->getParam("txtFromApply");
$to_apply = $this->dispatcher->getParam("txtToApply");

$urlPage = "?";
if(strlen($this->dispatcher->getParam("txtSearch"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $keyword));
}
if(strlen($from_apply) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtFromApply" => $from_apply));
}
if(strlen($to_apply) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtToApply" => $to_apply));
}
$from_payment = $this->dispatcher->getParam("txtFromPayment");
$to_payment = $this->dispatcher->getParam("txtToPayment");
if(strlen($from_payment) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtFromPayment" => $from_payment));
}
if(strlen($to_payment) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtToPayment" => $to_payment));
}
$method = $this->dispatcher->getParam("slcMethod");
if(strlen($method) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcActive" => $method));
}
$status = $this->dispatcher->getParam("slcStatus");
if(strlen($status) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcStatus" => $status));
}
$country = $this->dispatcher->getParam("slcCountry");
if(strlen($country) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcCountry" => $country));
}
$insurance = $this->dispatcher->getParam("cbInsurance");
if(strlen($insurance) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("cbInsurance" => $insurance));
}
$travel_sim = $this->dispatcher->getParam("cbTravelSim");
if(strlen($travel_sim) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("cbTravelSim" => $travel_sim));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Order</h3>
    </div>
</div>
<?php if(isset($msg_result['status'])) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<?php if(isset($msg_delete['error']) && !empty($msg_delete['error'])) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-error alert-dismissible fade in" role="alert">
        <?php echo $msg_delete['error']; ?>
    </div>
<?php } ?>
<?php if(isset($msg_delete['success']) && !empty($msg_delete['success'])) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $msg_delete['success']; ?>
    </div>
<?php } ?>
    <div class="clearfix"></div>
    <form class="searchForm" name="form-order" method="post">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row " style="padding-bottom: 10px">
                        <div class="col-md-2" style="display: flex">
                            <h2 style="display: inline-block; flex: 1 0 auto; margin-right: 10px">Keyword</h2>
                            <input class="form-control" type="text" name="txtSearch" maxlength="255" placeholder="ID, Name, Email" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>

                        <div class="col-md-2" style="display: flex">
                            <h2 style="display: inline-block; flex: 1 0 auto; margin-right: 10px">From Apply</h2>
                            <input name="txtFromApply" id="txtFromApply" autocomplete="off" type="text" class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii' placeholder="From Apply" value="<?php echo isset($from_apply) ? $from_apply : ''; ?>" >
                        </div>

                        <div class="col-md-2" style="display: flex">
                            <h2 style="display: inline-block; flex: 1 0 auto; margin-right: 10px">To Apply</h2>
                            <input name="txtToApply" id="txtToApply" autocomplete="off" type="text" class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii' placeholder="To Apply" value="<?php echo isset($to_apply) ? $to_apply : ''; ?>" >
                        </div>


                        <div class="col-md-3" style="display: flex">
                            <h2 style="display: inline-block; flex: 1 0 auto; margin-right: 10px">From Payment</h2>
                            <input name="txtFromPayment" id="txtFromPayment" autocomplete="off" type="text" class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii' placeholder="From Payment" value="<?php echo isset($from_payment) ? $from_payment : ''; ?>" >
                        </div>

                        <div class="col-md-3" style="display: flex">
                            <h2 style="display: inline-block; flex: 1 0 auto; margin-right: 10px">To Payment</h2>
                            <input name="txtToPayment" id="txtToPayment" autocomplete="off" type="text" class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii' placeholder="To Payment" value="<?php echo isset($to_payment) ? $to_payment : ''; ?>" >
                        </div>

                    </div>
                    <div class="row" style="display: flex">
                        <div class="col-md-2" style="display: flex">
                            <h2 style="display: inline-block; flex: 1 0 auto; margin-right: 10px">Method</h2>
                            <select class="form-control" name="slcMethod" id="slcMethod">
                                <?= Order::getMethodCombobox($method) ?>
                            </select>
                        </div>
                        <div class="col-md-2" style="display: flex">
                            <h2 style="display: inline-block; flex: 1 0 auto; margin-right: 10px">Status</h2>
                            <select class="form-control" name="slcStatus" id="slcStatus">
                                <?= Order::getStatusCombobox($status)?>
                            </select>
                        </div>
                        <div class="col-md-2" style="display: flex">
                            <h2 style="display: inline-block; flex: 1 0 auto; margin-right: 10px">Nationality</h2>
                            <select class="form-control" name="slcCountry" id="slcCountry">
                                <option value='0'>All Nationality</option>
                                <?= Country::getCombobox($country) ?>
                            </select>
                        </div>
                        <div class="col-md-3" style="display: flex; align-items: center;">
                            <label class='container_checkbox' style="padding-left: 20px; padding-right: 20px">Travel Sim
                                <input  <?php echo $travel_sim == 'Y' ? 'checked' : ''; ?> type="checkbox" value="Y" id="cbTravelSim" name="cbTravelSim" class='form-control check'>
                                <span class='checkmark_checkbox'></span>
                            </label>
                            <label class='container_checkbox' style="padding-left: 20px; padding-right: 20px">Insurance
                                <input  <?php echo $insurance == 'Y' ? 'checked' : ''; ?> type="checkbox" value="Y" id="cbInsurance" name="cbInsurance" class='form-control check'>
                                <span class='checkmark_checkbox'></span>
                            </label>
                        </div>
                        <div class="col-md-3">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                            <button type="submit" name="btnExportcsv" title="" class="btn btn-warning ">Export to CSV</button>
                        </div>

                    </div>
                    <div>
                        <strong>Total</strong>
                        <?= $total_record ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header">
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input type="checkbox" id="checkboxAll"><span class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID </th>
                                <th class="column-title">Name </th>
                                <th width="50px" class="column-title">Total </th>
                                <th width="160px" class="column-title">Apply Date </th>
                                <th width="160px" class="column-title">Payment Date </th>
                                <th width="260px" class="column-title">Method </th>
                                <th width="50px" class="column-title">Status </th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action </span></th>
                            </tr>
                            </thead>
                            <tbody class="tb_body">
                            <?php
                            foreach ($list_order as $item ) {
                                ?>
                                <tr>
                                    <td><label class="container_checkbox"><input class="check" name="item[]" value="<?= $item->order_id ?>" type="checkbox"><span class="checkmark_checkbox"></span></label></td>
                                    <td class=" ">#<?= $item->order_id  ?></td>
                                    <td class=" "><?= User::getNameById($item->order_user_id) ?></td>
                                    <td class="text-right "><?= $this->my->formatUSD($item->order_total) ?></td>
                                    <td class=" "><?= $this->my->formatDateTime($item->order_register_date) ?></td>
                                    <td class=" "><?php echo ($item->receipt_pay_date>0)? $this->my->formatDateTime($item->receipt_pay_date):'' ?></td>
                                    <td><?=$this->my->getMethod($item->order_payment_method, $item->order_cardtype, $item->order_isenrolled3d, $item->order_ispassed3d, true) ?></td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $classStatus = 'default';
                                        if($item->order_status == 'Pending') {
                                            $classStatus = 'danger';
                                        } else if ($item->order_status == 'Success') {
                                            $classStatus = 'success';
                                        }
                                        ?>
                                        <span class="label label-<?= $classStatus; ?>"><?= $item->order_status; ?></span>
                                    </td>
                                    <td class="last">
                                        <a class="btn btn-primary btn-xs margin-0" style="" href="<?= $this->url->get("/order/view?id=".$item->order_id) ?>">View</a>
                                    </td>
                                </tr>

                            <?php }?>
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-6 ">
                    </div>
                    <div class="col-md-6 pull-right">
                        <?php if($total_page > 1) {?>
                            <nav class="paginate-footer">
                                <?php  if($urlPage != "?") $urlPage .= "&";
                                $urlPage .= "page=";
                                echo $this->my->renderPagination($urlPage, $current_page, $total_page, 2);
                                ?>
                            </nav>
                        <?php }?>
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
    </form>
    <script>
        $(document).ready(function(){
            $('button[name=search]').click(function() {
                $('form[name=form-order]').prop('action','<?php echo $this->url->get('/order'); ?>');
                $('form[name=form-order]').submit();
            });
            $('button[name=btnExportcsv]').click(function() {
                $('form[name=form-order]').prop('action','<?php echo $this->url->get('/order/exportcsv'); ?>');
                $('form[name=form-order]').submit();
            });

        });
    </script>

