<?php
$urlPage = "?";
if (strlen($this->dispatcher->getParam("country")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slCountry" => $this->dispatcher->getParam("country")));
}
if (strlen($this->dispatcher->getParam("lang_code")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slLanguage" => $this->dispatcher->getParam("lang_code")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Location</h3>
    </div>
</div>
<?php if (isset($msg_result)) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<?php $message_success = isset($msg_del["success"]) ? $msg_del["success"] : '';
$message_error = isset($msg_del["error"]) ? $msg_del["error"] : '';
if (!empty($message_success)) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $message_success; ?>
    </div>
<?php }
if (!empty($message_error)) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-error alert-dismissible fade in" role="alert">
        <?php echo $message_error; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-location" method="post" action="">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <h2>Country</h2>
                        <div class="col-md-2">
                            <select class="form-control" name="slCountry" id="slCountrySearch">
                                <?php echo isset($slCountry) ? $slCountry : '' ?>
                            </select>
                        </div>
                        <h2>Language</h2>
                        <div class="col-md-2">
                            <select class="form-control" name="slLanguage" id="slLanguage">
                                <option value="">All Language</option>
                                <?php echo isset($slLanguage) ? $slLanguage : '' ?>
                            </select>
                        </div>
                        <div class="col-md-2">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                            <a class="btn btn-info" href="<?php echo $this->url->get("/location/create"); ?>">Add
                                New</a>
                        </div>

                    </div>
                    <div>
                        <strong>Total</strong>
                        <?php echo $list_location->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header">
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input
                                                type="checkbox" id="checkboxAll"><span
                                                class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID</th>
                                <th class="column-title">Country</th>
                                <th width="150px" class="column-title">Language</th>
                                <th width="100px" class="column-title">Hreflang</th>
                                <th width="50px" class="column-title">Order</th>
                                <th width="50px" class="column-title">Active</th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>

                            <tbody class="tb_body">
                            <?php foreach ($list_location->items as $item) {
                                ?>
                                <tr>

                                    <td><label class="container_checkbox"><input class="check" name="item[]"
                                                                                 value="<?php echo $item->getLocationId() ?>"
                                                                                 type="checkbox"><span
                                                    class="checkmark_checkbox"></span></label></td>
                                    <td class=" "><?php echo $item->getLocationId() ?></td>
                                    <td class=" "><?php echo \Indianimmigrationorg\Repositories\CountryGeneral::getCountryNameOrGlobalByCode($item->getLocationCountryCode()) ." (".strtoupper($item->getLocationCountryCode()).")" ?></td>
                                    <td class=" "><?php echo \Indianimmigrationorg\Repositories\Language::getNameByCode($item->getLocationLangCode())." (".strtoupper($item->getLocationLangCode()).")" ?></td>
                                    <td class="text-center"><?php echo $item->getLocationAlternateHrefLang() ?></td>
                                    <td class="text-center"><?php echo $item->getLocationOrder() ?></td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getLocationActive();
                                        $classStatus = ($status == "Y") ? "success" : "danger";
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td><a class="btn btn-primary btn-xs margin-0"
                                           href="<?php echo $this->url->get("/location/edit?id=" . $item->getLocationId()); ?> ">View</a>
                                    </td>
                                </tr>

                            <?php } ?>
                            </tbody>
                        </table>

                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <label for="slcAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction"
                                    style="display: inline-block;width: 40%">
                                <option value="" selected>Please select</option>
                                <option value="drop">Drop</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <?php if ($list_location->total_pages > 1) { ?>
                                <nav class="paginate-footer">
                                    <?php if ($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $list_location->current, $list_location->total_pages, 2);
                                    ?>
                                </nav>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <h2>List link:</h2>
    <table class="table table-striped table-bordered">
        <tr>
            <th>Country Name</th>
            <th>URL</th>
            <th>Sitemap </th>
        </tr>
        <?php
        $link = URL_SITE;
        foreach ($list_location->items as $item) {
            /**
             * @var \Indianimmigrationorg\Models\VisaLocation $item
             */
            $country_code =$item->getLocationCountryCode();
            $linkGX =($country_code=='gx')?'':'-'.$country_code;
            ?>
            <tr>
                <td><?= \Indianimmigrationorg\Repositories\CountryGeneral::getCountryNameOrGlobalByCode($item->getLocationCountryCode())?></td>
                <td><a target="_blank" href="<?= $link . '/' . $item->getLocationCountryCode() . '-' . $item->getLocationLangCode() ?>">
                        <?= $link . '/' . $item->getLocationLangCode(). $linkGX  ?>
                    </a></td>
                <td><a target="_blank" href="sitemap: <?= $link . '/' . $item->getLocationCountryCode() . '/' . $item->getLocationLangCode(). '/sitemap/sitemap-' . $item->getLocationLangCode().$linkGX.'.xml'?>">
                        <?= $link . '/' .  $item->getLocationLangCode(). $linkGX.'/sitemap/sitemap-' . $item->getLocationLangCode().$linkGX.'.xml'?>
                    </a></td>
            </tr>
        <?php } ?>
    </table>
    <h2>Sitemap:</h2>
    <table class="table table-striped table-bordered">
        <tr>
            <th>URL</th>
        </tr>
        <?php foreach ($list_location->items as $item) {
            /**
             * @var \Indianimmigrationorg\Models\VisaLocation $item
             */
            $country_code =$item->getLocationCountryCode();
            $linkGX =($country_code=='gx')?'':'-'.$country_code;
            ?>
            <tr>
                <td><a target="_blank" href="sitemap: <?= $link . '/' . $item->getLocationLangCode().$linkGX. '/sitemap/sitemap-' . $item->getLocationLangCode().$linkGX.'.xml'?>">
                        sitemap: <?= $link . '/' . $item->getLocationLangCode().$linkGX. '/sitemap/sitemap-' . $item->getLocationLangCode().$linkGX.'.xml'?>
                    </a></td>
            </tr>
        <?php } ?>
    </table>
</form>
<script>
    $(document).ready(function () {
        $('button[name=search]').click(function () {
            $('form[name=form-location]').prop('action', '<?php echo $this->url->get('/location'); ?>');
            $('form[name=form-location]').submit();
        });
        $('.delete-all').click(function () {
            $('form[name=form-location]').prop('action', '<?php echo $this->url->get('/location/delete'); ?>');
            $('form[name=form-location]').submit();
        });
    });
</script>