<script>
    $( document ).ready(function() {
        $('form[name=location-form]').submit(function(event) {
            var valid = true;
            if($('select[name=slcCountry]').val() == '') {
                $('.msg-country').text('Country field is required.');
                $('#slcCountry').addClass("border-red");
                valid = false;
            } else {
                $('.msg-country').text('');
                $('#slcCountry').removeClass("border-red");
            }
            if($('select[name=slcLanguage]').val() == '') {
                $('.msg-language').text('Language field is required.');
                $('#slcLanguage').addClass("border-red");
                valid = false;
            }  else {
                $('.msg-language').text('');
                $('#slcLanguage').removeClass("border-red");
            }
            if($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=submit]').prop('disabled', true);
            }
        });
    });

</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Location</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">
                <h2 class="form_title"></h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br />
                <form name="location-form" id="location-form" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="country-code">Country <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcCountry" name="slcCountry" class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["country"])) ? $messages["status"] : ""; ?>">
                                <option value=''>Select Country...</option>
                                <?php
                                echo isset($select_country) ? $select_country : "";
                                ?>
                            </select>
                            <span class="text-danger msg-country"><?php echo isset($messages["country"]) ? $messages["country"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="country-code">Language <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select class="form-control <?php echo (isset($messages["language"])) ? $messages["status"] : ""; ?> " name="slcLanguage" id="slcLanguage">
                                <option value=''>Select Language. . . </option>
                                <?php
                                echo \Indianimmigrationorg\Repositories\Language::getCombo($formData["location_lang_code"]);
                                ?>
                            </select>
                            <span class="text-danger msg-language"><?php echo isset($messages["language"]) ? $messages["language"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Alternate HrefLang </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10" value="<?php echo isset($formData["location_alternate_hreflang"]) ? $formData["location_alternate_hreflang"] : "" ?>" id="txtAlternateHrefLang" name="txtAlternateHrefLang"   class="form-control col-md-7 col-xs-12 "   type="text">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Schema Contactpoint  </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea id="txtSchemaContactpoint" name="txtSchemaContactpoint" class="form-control"><?php echo isset($formData["location_schema_contactpoint"]) ? $formData["location_schema_contactpoint"] : "" ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Schema Social  </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea id="txtSchemaSocial" name="txtSchemaSocial" class="form-control"><?php echo isset($formData["location_schema_social"]) ? $formData["location_schema_social"] : "" ?></textarea>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10" value="<?php echo isset($formData["location_order"]) ? $formData["location_order"] : "" ?>" id="txtOrder" name="txtOrder"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $messages["status"] : ""; ?>"   type="text">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : "";?></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["location_active"]) && $formData["location_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["location_active"]) && $formData["location_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="submit" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="/location">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>