<?php
$urlPage = "?";
if(strlen($this->dispatcher->getParam("txtSearch"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
if($this->dispatcher->getParam("slNewspaper") != ""){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slNewspaper" => $this->dispatcher->getParam("slNewspaper")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Newspaper Article</h3>
    </div>
</div>
<?php if(isset($msg_result['status'])) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<?php if(isset($msg_delete['error']) && !empty($msg_delete['error'])) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-error alert-dismissible fade in" role="alert">
        <?php echo $msg_delete['error']; ?>
    </div>
<?php } ?>
<?php if(isset($msg_delete['success']) && !empty($msg_delete['success'])) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $msg_delete['success']; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-newspaper-article" method="post">
    <?php
        $keyword = $this->dispatcher->getParam("txtSearch");
        $slNewspaper = $this->dispatcher->getParam("slNewspaper");
    ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2>Keyword</h2>
                        </div>
                        <div class="col-md-3">
                            <input class="form-control" type="text" name="txtSearch" maxlength="255" placeholder="ID, Name, Link" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <h2>Newspaper</h2>
                        <div class="col-md-3">
                            <select class="form-control" name="slNewspaper" id="slNewspaper">
                                <option value="0">All Newspaper</option>
                                <?php
                                    echo isset($select_newspaper) ? $select_newspaper : "";
                                ?>
                            </select>
                        </div>
                        <div class="col-md-1">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                        </div>
                        <div class="col-md-2 pull-right text-right">
                            <a class="btn btn-info" href="<?php echo $this->url->get("/newspaperarticle/create"); ?>">Add New</a>
                        </div>
                    </div>
                    <div>
                        <strong>Total</strong>
                        <?php echo $article_list->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header">
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input type="checkbox" id="checkboxAll"><span class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID</th>
                                <th class="column-title">Name</th>
                                <th class="column-title">Newspaper</th>
                                <th width="160px" class="column-title">Update Time</th>
                                <th width="50px" class="column-title">Order</th>
                                <th width="50px" class="column-title">Active</th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>

                            <tbody class="tb_body">
                            <?php foreach ($article_list->items as $item ) { ?>
                                <?php
                                /**
                                 * @var \Indianimmigrationorg\Models\VisaNewspaperArticle $item
                                 */
                                ?>
                                <tr>
                                    <td>
                                        <label class="container_checkbox">
                                            <input class="check" name="item[]" id="type-checkbox<?php echo $item->getArticleId(); ?>" value="<?php echo $item->getArticleId(); ?>" type="checkbox">
                                            <span class="checkmark_checkbox"></span>
                                        </label>
                                    </td>
                                    <td class=" "><?php echo $item->getArticleId(); ?></td>
                                    <td class=" "><?php echo $item->getArticleName(); ?></td>
                                    <td class=" "><?php echo Indianimmigrationorg\Repositories\Newspaper::getNameByID($item->getArticleNewspaperId()) ?></td>
                                    <td class=" "><?php echo $this->my->formatDateTime($item->getArticleUpdateTime()); ?></td>
                                    <td class="text-center"><?php echo $item->getArticleOrder() ?></td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getArticleActive();
                                        $classStatus = ($status == "Y") ? "success" : "danger" ;
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>                                    <td class="last">
                                        <a class="btn btn-primary btn-xs margin-0" style="" href="<?php echo $this->url->get("/newspaperarticle/edit?id=".$item->getArticleId()); ?>">View</a>
                                    </td>
                                </tr>
                            <?php }?>
                            </tbody>
                        </table>

                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <label for="slcAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction" style="display: inline-block;width: 40%">
                                <option value="" selected >Please select</option>
                                <option value="drop">Drop</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <?php if($article_list->total_pages > 1) {?>
                                <nav class="paginate-footer">
                                    <?php  if($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $article_list->current, $article_list->total_pages, 2);
                                    ?>
                                </nav>
                            <?php }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function(){
        $('button[name=search]').click(function() {
            $('form[name=form-newspaper-article]').prop('action','<?php echo $this->url->get('/newspaperarticle'); ?>');
            $('form[name=form-newspaper-article]').submit();
        });

        $('.delete-all').click(function(){
            $('form[name=form-newspaper-article]').prop('action','<?php echo $this->url->get('/newspaperarticle/delete'); ?>');
            $('form[name=form-newspaper-article]').submit();
        });
    });
</script>