<?php
    header("X-Frame-Options: SAMEORIGIN");
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>India</title>

    <link rel="shortcut icon" href="<?php echo $this->url->getStatic('favicon.ico') ?>?<?php echo time(); ?>">
    <!-- Bootstrap -->
    <link href="<?php echo $this->url->getStatic('shared/css/'); ?>bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?php echo $this->url->getStatic('shared/fonts/'); ?>font-awesome.min.css" rel="stylesheet">
    <!-- jQuery custom content scroller -->
    <link href="<?php echo $this->url->getStatic('backend/css/'); ?>jquery.mCustomScrollbar.min.css" rel="stylesheet"/>
    <!--   Datetime -->
    <link rel="stylesheet" href="<?php echo $this->url->getStatic("/backend/css/datepicker.min.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->url->getStatic("/shared/css/jquery-ui-1.12.1.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->url->getStatic("/backend/css/jquery.timepicker.css"); ?>">
    <link rel="stylesheet" href="<?php echo $this->url->getStatic("/backend/js/select2/select2.min.css"); ?>">

    <!-- Custom Theme Style -->
    <link href="<?php echo $this->url->getStatic('backend/css/'); ?>custom.min.css" rel="stylesheet">
    <link href="<?php echo $this->url->getStatic('backend/css/'); ?>style.css?v=<?php echo time(); ?>" rel="stylesheet">
    <link href="<?php echo $this->url->getStatic('backend/css/'); ?>typeaheadjs.css?v=<?php echo time(); ?>" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo $this->url->getStatic("/backend/css/intlTelInput.min.css"); ?>">
    <!-- jQuery -->
    <script src="<?php echo $this->url->getStatic('backend/js/'); ?>jquery.min.js"></script>
    <script src="<?php echo $this->url->getStatic('backend/fckeditor/fckeditor.js'); ?>"></script>
    <script src="<?php echo $this->url->getStatic('backend/js/intlTelInput.min.js'); ?>"></script>
    <script src="<?php echo $this->url->getStatic('shared/')?>js/jquery.validate.js"></script>
    <script src="<?php echo $this->url->getStatic('shared/js/');?>jquery-ui-1.12.1.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->url->getStatic("backend/js/select2/select2.min.js"); ?>"></script>
    <script>
        var DASHBOARD_URL = "<?php echo $this->url->get('/'); ?>";
    </script>
</head>
<body class="nav-md">
<div class="container body">
    <div class="main_container">
        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav>
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                               aria-expanded="false">
                                <?php $auth = $this->session->get('auth');
                                echo $auth["role"]; ?>
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="<?php echo $this->url->get("/logout"); ?>"><i
                                                class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->