<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Promotion Template</h3>
    </div>
</div>
<?php if(!empty($messages['message']))
{
    ?>
    <div class="clearfix"></div>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage']?>">
        <?php echo $messages['message']; ?>
    </p>
<?php }	?>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <ul class="nav nav-pills" role="tablist">
                <?php
                foreach ( $formData['arr_language'] as $code => $lang ){
                    $active = $formData['lang_current']== $code?"active":"";
                    ?>
                    <li role="presentation" class="<?php echo $active; ?>"><a href="#<?php echo $code ?>translate" aria-controls="<?php echo $code ?>translate" role="tab" data-toggle="tab"><?php echo strtoupper($code).' - '
                                .$lang;
                            ?></a></li>
                <?php } ?>
            </ul>
            <div class="tab-content">
                <?php foreach ($formData['arr_language'] as $code => $lang ) {
                    $active = $formData['lang_current']== $code?"active":"";
                    ?>
                    <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                        <br>
                        <form name="promotion-template-form<?php echo $code; ?>" id="promotion-template-form<?php echo $code; ?>" action="" data-parsley-validate class="form-horizontal form-label-left" method="post">
                            <input type="hidden" name="save" id="save" value="<?php echo $code; ?>" />
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtSubject">Title
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255" value="<?php echo isset($formData['arr_translate'][$code]["template_title"]) ? $formData['arr_translate'][$code]["template_title"] : "" ?>" type="text" id="txtTitle" name="txtTitle" class="form-control col-md-7 col-xs-12" />
                                    <span class="text-danger msg-title-<?php echo $code; ?>"><?php echo isset($messages[$code]["title"]) ? $messages[$code]["title"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtContent">Content
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea class="form-control"  id="txtContent" name ="txtContent" style=" height: 212px;"><?php echo isset($formData['arr_translate'][$code]["template_content"]) ? $formData['arr_translate'][$code]["template_content"] : ""; ?></textarea>
                                    <span class="text-danger msg-content-<?php echo $code; ?>"><?php echo isset($messages[$code]["content"]) ? $messages[$code]["content"] : ""; ?></span>
                                </div>
                            </div>

                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button name="sbmEmailtempalte<?php echo $code; ?>" type="submit" class="btn btn-success">
                                        <?php echo 'Save (' . $lang.')'; ?>
                                    </button>
                                </div>
                            </div>
                            <script>
                                $( document ).ready(function() {
                                    
                                    $('form[name=promotion-template-form<?php echo $code; ?>]').submit(function (event) {
                                        valid = true;
                                        if ($('#txtTitle<?php echo $code; ?>').val() == '') {
                                            valid = false;
                                            $('.msg-title-<?php echo $code;?>').text("Title field is required.");
                                            $('#txtTitle<?php echo $code; ?>').addClass("border-red");
                                        } else {
                                            $('.msg-title-<?php echo $code;?>').text('');
                                            $('#txtTitle<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtContent<?php echo $code; ?>').val() == '') {
                                            $('.msg-content-<?php echo $code; ?>').text('Content field is required.');
                                            $('#txtContent<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-content-<?php echo $code; ?>').text('');
                                            $('#txtContent<?php echo $code; ?>').removeClass("border-red");
                                        }
                                                                            
                                        $('#sbmEmailtempalte<?php echo $code; ?>').prop('disabled', true);
                                    });
                                });
                            </script>
                        </form>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>
