<?php
$urlPage = "?";
if(strlen($this->dispatcher->getParam("txtSearch"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Newspaper</h3>
    </div>
</div>
<?php if (isset($msg_result['status'])) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<?php if (isset($msg_delete['status'])) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-<?php echo $msg_delete['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_delete['msg']; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-newspaper" method="post" action="">
    <?php $keyword = $this->dispatcher->getParam("txtSearch");
    ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2 class="">Keyword</h2>
                        </div>
                        <div class="col-md-2">
                            <input maxlength="255" class="form-control" type="text" name="txtSearch" placeholder="ID, Name" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <div class="col-md-1">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                        </div>
                        <div class="col-md-1 pull-right text-right">
                            <a class="btn btn-info" href="<?php echo $this->url->get("/newspaper/create"); ?>">Add New</a>
                        </div>
                    </div>
                    <div >
                        <strong>Total</strong>
                        <?php echo $list_newspaper->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header" >
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input type="checkbox" id="checkboxAll"><span class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID </th>
                                <th width="" class="column-title">Name </th>
                                <th width="" class="column-title">Location Country </th>
                                <th width="160px" class="column-title">Update Time </th>
                                <th width="50px" class="column-title">Order </th>
                                <th width="50px" class="column-title">Active </th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>

                            <tbody class="tb_body">
                            <?php foreach ($list_newspaper->items as $item) { ?>
                                <?php
                                /**
                                 * @var Indianimmigrationorg\Models\VisaNewspaper $item
                                 */

                                ?>
                                <tr >
                                    <td><label class="container_checkbox"><input class="check" name="item[]" value="<?php echo $item->getNewspaperId() ?>" type="checkbox"><span class="checkmark_checkbox"></span></label></td>
                                    <td class=" "><?php echo $item->getNewspaperId() ?></td>
                                    <td class=" "><?php echo $item->getNewspaperName() ?></td>
                                    <td class=" "><?php echo \Indianimmigrationorg\Repositories\CountryGeneral::getCountryNameOrGlobalByCode($item->getNewspaperLocationCountryCode()) ?></td>
                                    <td class=" "><?php echo $this->my->formatDateTime($item->getNewspaperUpdateTime()); ?></td>
                                    <td class="text-center"><?php echo $item->getNewspaperOrder() ?></td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getNewspaperActive();
                                        $classStatus = ($status == "Y") ? "success" : "danger" ;
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td><a class="btn btn-primary btn-xs margin-0" href="<?php echo $this->url->get("/newspaper/edit?id=".$item->getNewspaperId()); ?> ">View</a>
                                    </td>
                                </tr>
                            <?php }?>
                            </tbody>
                        </table>

                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <label for="slcAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction" style="display: inline-block;width: 40%">
                                <option value="" selected>Please select</option>
                                <option value="drop">Drop</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <?php if($list_newspaper->total_pages > 1) {?>
                                <nav class="paginate-footer">
                                    <?php  if($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $list_newspaper->current, $list_newspaper->total_pages,2);
                                    ?>
                                </nav>
                            <?php }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function(){
        $('button[name=search]').click(function() {
            $('form[name=form-newspaper]').prop('action','<?php echo $this->url->get('/newspaper'); ?>');
            $('form[name=form-newspaper]').submit();
        });

        $('.delete-all').click(function(){
            $('form[name=form-newspaper]').prop('action','<?php echo $this->url->get('/newspaper/delete'); ?>');
            $('form[name=form-newspaper]').submit();
        });
    });
</script>