<script>
    $( document ).ready(function() {
        var id = "<?= isset($formData["newspaper_id"] ) ? $formData["newspaper_id"]  : -1?>";
        $('#txtName').on('input', function() {
            var str = $(this).val();
            if(id == -1) {
                var str_slug = slugify(str);
                $('#txtKeyword').val(str_slug);
                $('#txtTitle').val(str);
                $('#txtMetaKey').val(str);
                $('#txtMetaDesc').val(str);
            }
        });
        $('form[name=newspaper-form]').submit(function(event) {
            var valid = true;

            if($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Name field is required.');
                $('#txtName').addClass("border-red");
                valid = false;
            } else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }

            if($('select[name=slcLocationCountry]').val() == '') {
                $('.msg-country').text('Location Country field is required.');
                $('#slcLocationCountry').addClass("border-red");
                valid = false;
            } else {
                $('.msg-country').text('');
                $('#slcLocationCountry').removeClass("border-red");
            }
            if($('input[name=txtKeyword]').val() == '') {
                $('.msg-keyword').text('Keyword field is required.');
                $('#txtKeyword').addClass("border-red");
                valid = false;
            } else {
                $('.msg-keyword').text('');
                $('#txtKeyword').removeClass("border-red");
            }
            if($('input[name=txtTitle]').val() == '') {
                $('.msg-title').text('Title field is required.');
                $('#txtTitle').addClass("border-red");
                valid = false;
            } else {
                $('.msg-title').text('');
                $('#txtTitle').removeClass("border-red");
            }
            if($('input[name=txtMetaKey]').val() == '') {
                $('.msg-metakeyword').text('Meta keyword field is required.');
                $('#txtMetaKey').addClass("border-red");
                valid = false;
            } else {
                $('.msg-metakeyword').text('');
                $('#txtMetaKey').removeClass("border-red");
            }
            if($('input[name=txtMetaDesc]').val() == '') {
                $('.msg-metadescription').text('Meta description field is required.');
                $('#txtMetaDesc').addClass("border-red");
                valid = false;
            } else {
                $('.msg-metadescription').text('');
                $('#txtMetaDesc').removeClass("border-red");
            }
            if($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=sbmNewspaper]').prop('disabled', true);
            }
        });
    });
</script>

<div class="page-title">
    <div class="title_left">
        <h3 class="article-type-title">Newspaper </h3>
    </div>
</div>
<?php if(isset($msg_result))  {?>
    <div class="clearfix"></div>
    <div  class="alert alert-<?php echo $msg_result['status']?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title"><?php echo isset($title)? $title:'' ;
                $messages['status'] = 'border-red';?></div>
            <div class="x_content">
                <br />
                <form name="newspaper-form" id="newspaper-form" action="" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="country-code">Location Country <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcLocationCountry" name="slcLocationCountry" class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["newspaper_location_country_code"])) ? $messages["status"] : ""; ?>">
                                <option value=''>Select Country...</option>
                                <?php
                                echo isset($select_country) ? $select_country : "";
                                ?>
                            </select>
                            <span class="text-danger msg-country"><?php echo isset($messages["newspaper_location_country_code"]) ? $messages["newspaper_location_country_code"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtName">Name <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["newspaper_name"]) ? $formData["newspaper_name"] : "" ?>" type="text" id="txtName" name="txtName"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["name"])) ? $messages['status'] : ""; ?>">
                            <span class="text-danger msg-name"><?php echo isset($messages["name"]) ? $messages["name"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtKeyword">Alias URL <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["newspaper_keyword"]) ? $formData["newspaper_keyword"] : "" ?>" type="text" id="txtKeyword" name="txtKeyword"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["keyword"])) ? $messages['status'] : ""; ?>">
                            <span class="text-danger msg-keyword"><?php echo isset($messages["keyword"]) ? $messages["keyword"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtTitle">Title <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["newspaper_title"]) ? $formData["newspaper_title"] : "" ?>" type="text" id="txtTitle" name="txtTitle"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["title"])  ) ? $messages['status'] : ""; ?>">
                            <span class="text-danger msg-title"><?php echo isset($messages["title"]) ? $messages["title"] : "";?></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtMetaKey">Meta keyword <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["newspaper_meta_keyword"]) ? $formData["newspaper_meta_keyword"] : "" ?>" type="text" id="txtMetaKey" name="txtMetaKey"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["meta_keyword"])) ? $messages['status'] : ""; ?>">
                            <span class="text-danger msg-metakeyword"><?php echo isset($messages["meta_keyword"]) ? $messages["meta_keyword"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtMetaDesc">Meta description <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["newspaper_meta_description"]) ? $formData["newspaper_meta_description"] : "" ?>" type="text" id="txtMetaDesc" name="txtMetaDesc"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["meta_description"])) ? $messages['status'] : ""; ?>">
                            <span class="text-danger msg-metadescription"><?php echo isset($messages["meta_description"]) ? $messages["meta_description"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtLogo">Logo </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["newspaper_logo"]) ? $formData["newspaper_logo"] : "" ?>" type="text" id="txtLogo" name="txtLogo"   class="form-control col-md-7 col-xs-12 ">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtLink">Link </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["newspaper_link"]) ? $formData["newspaper_link"] : "" ?>" type="text" id="txtLink" name="txtLink"   class="form-control col-md-7 col-xs-12 ">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta image</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input placeholder="1920 x 960" maxlength="255" value="<?php echo isset($formData["newspaper_meta_image"]) ? $formData["newspaper_meta_image"] : "" ?>" id="txtMetaImage" name="txtMetaImage" class="form-control col-md-7 col-xs-12" type="text" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtOrder">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10" value="<?php echo isset($formData["newspaper_order"]) ? $formData["newspaper_order"] : "" ?>" type="text" id="txtOrder" name="txtOrder"  class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $messages['status'] : ""; ?>">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["newspaper_active"]) && $formData["newspaper_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["newspaper_active"]) && $formData["newspaper_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmNewspaper" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="<?php echo $this->url->get('/newspaper'); ?>">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
