<script>
    $( document ).ready(function() {
        $('form[name=country-form]').submit(function(event) {
            var valid = true;
            if($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Name field is required.');
                $('#txtName').addClass("border-red");
                valid = false;
            } else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }
            if($('input[name=txtCode]').val() == '') {
                $('.msg-code').text('Code field is required.');
                $('#txtCode').addClass("border-red");
                valid = false;
            } else {
                $('.msg-code').text('');
                $('#txtCode').removeClass("border-red");
            }
            if ($('input[name=txtValue]').val() == '') {
                $('.msg-value').text('Value field is required.');
                $('#txtValue').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtValue]').val())) {
                $('.msg-value').text('Enter a valid Value.');
                $('#txtValue').addClass("border-red");
                valid = false;
            } else {
                $('.msg-value').text('');
                $('#txtValue').removeClass("border-red");
            }

            if ($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if( ! valid )
            { event.preventDefault();}
            if( valid ) {
                $('button[name=sbmCountry]').prop('disabled', true);
            }
        });
    });
</script>

<div class="page-title">
    <div class="title_left">
        <h3 class="country-title">Country</h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Create</div>
            <div class="x_content">
                <br />
                <form name="country-form" id="country-form" action="<?php echo $this->url->get('/country/create'); ?>" data-parsley-validate class="form-horizontal form-label-left" method="post">


                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtName">Name <span class="red">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["country_name"]) ? $formData["country_name"] : "" ?>" type="text" id="txtName" name="txtName" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["name"]) ? $messages["status"] : ""; ?>" />
                            <span class="text-danger msg-name"><?php echo isset($messages["name"]) ? $messages["name"] : ""?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtCode">Code <span class="red">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="2" value="<?php echo isset($formData["country_code"]) ? $formData["country_code"] : "" ?>" type="text" id="txtCode" name="txtCode" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["code"]) ? $messages["status"] : ""; ?>" />
                            <span class="text-danger msg-code"><?php echo isset($messages["code"]) ? $messages["code"] : ""?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="txtValue">Value <span class="red">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10" value="<?php echo isset($formData["country_value"]) ? $formData["country_value"] : "" ?>" type="text" id="txtValue" name="txtValue" class="form-control col-md-7 col-xs-12 <?php echo isset($messages["value"]) ? $messages["status"] : ""; ?> " />
                            <span class="text-danger msg-value"><?php echo isset($messages["value"]) ? $messages["value"] : ""?></span>
                         </div>
                        <div class="col-md-3">
                            <dl style="color:#F00; display: flex;">
                                <dt style="padding-right: 15px;">Note :</dt>
                                <dd>
                                    0 = This is value of Normal Country
                                    <br>
                                    1 = This is value of Accepted Country
                                    <br>
                                    2 = This is value of Exception Country
                                </dd>
                            </dl>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Order <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10"
                                   value="<?php echo isset($formData["country_order"]) ? $formData["country_order"] : "" ?>"
                                   id="txtOrder" name="txtOrder"
                                   class="form-control col-md-7 col-xs-12 <?php echo isset($messages["country_order"])  ? $messages["status"] : ""; ?>"
                                   type="text">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : ""; ?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Active</label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["country_active"]) && $formData["country_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["country_active"]) && $formData["country_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmCountry" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="/country">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
