<?php
$urlPage = "?";
if(strlen($this->dispatcher->getParam("txtSearch"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>Country</h3>
    </div>
</div>
<?php if(isset($msg_result))  {?>
    <div class="clearfix"></div>
    <div  class="alert alert-<?php echo $msg_result['status']?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-country" method="post" action="">
    <?php $keyword = $this->dispatcher->getParam("txtSearch");
    ?>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                        <div class="col-md-1">
                            <h2 class="">Keyword</h2>
                        </div>
                        <div class="col-md-4">
                            <input maxlength="255" class="form-control" type="text" name="txtSearch" placeholder="ID, Name" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <h2>Language</h2>
                        <div class="col-md-3">
                            <select class="form-control" name="slcLang" id="slcLang">
                                <?php
                                echo isset($select_lang) ? $select_lang : "";
                                ?>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                            <a class="btn btn-info" href="<?php echo $this->url->get("/country/create"); ?>">Add New</a>
                        </div>

                    </div>
                    <div >
                        <strong>Total</strong>
                        <?php echo $list_country->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header" >
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input type="checkbox" id="checkboxAll"><span class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID </th>
                                <th class="column-title">Code</th>
                                <th class="column-title">Name</th>
                                <th class="column-title">Value</th>
                                <th width="50px" class="column-title">Order </th>
                                <th width="50px" class="column-title">Active </th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>

                            <tbody class="tb_body">
                            <?php foreach ($list_country->items as $item) {
                                ?>
                                <tr >
                                    <td><label class="container_checkbox"><input class="check" name="item[]" value="<?php echo $item->getCountryId(); ?>" type="checkbox"><span class="checkmark_checkbox"></span></label></td>
                                    <td class=" "><?php echo $item->getCountryId(); ?></td>
                                    <td class=" "><?php echo $item->getCountryCode(); ?></td>
                                    <td class=" "><?=  $item->getCountryName(); ?></td>
                                    <td class=" "><?=  $item->getCountryValue(); ?></td>
                                    <td class=" "><?=  $item->getCountryOrder(); ?></td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $active = $item->getCountryActive();
                                        $classAcitve = ($active == "Y") ? "success" : "danger" ;
                                        ?>
                                        <span class="label label-<?php echo $classAcitve; ?>"><?php echo $active; ?></span>
                                    </td>
                                    <td><a class="btn btn-primary btn-xs margin-0"   href="<?php echo $this->url->get("/country/edit?id=".$item->getCountryId()); ?> ">View</a>
                                    </td>
                                </tr>

                            <?php }?>
                            </tbody>
                        </table>

                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <label for="slAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction" style="display: inline-block;width: 40%">
                                <option value="" selected >Please select</option>
                                <option value="drop">Drop</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <?php if($list_country->total_pages > 1) {?>
                                <nav class="paginate-footer">
                                    <?php  if($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $list_country->current, $list_country->total_pages,2);
                                    ?>
                                </nav>
                            <?php }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function(){
        $('button[name=search]').click(function() {
            $('form[name=form-country]').prop('action','<?php echo $this->url->get('/country'); ?>');
            $('form[name=form-country]').submit();
        });

        $('.delete-all').click(function(){
            $('form[name=form-country]').prop('action','<?php echo $this->url->get('/country/delete'); ?>');
            $('form[name=form-country]').submit();
        });
    });
</script>