<?php
$keyword =$this->dispatcher->getParam("txtSearch");
$from = $this->dispatcher->getParam("txtFrom");
$to = $this->dispatcher->getParam("txtTo");
$urlPage = "?";
if(strlen($this->dispatcher->getParam("txtSearch"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $keyword));
}
if(strlen($this->dispatcher->getParam("txtFrom")) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtFrom" => $from));
}
if(strlen($this->dispatcher->getParam("txtTo")) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtTo" => $to));
}
$active = $this->dispatcher->getParam("slcActive");
if(strlen($active) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcActive" => $active));
}
$subscribe = $this->dispatcher->getParam("slcSubscribe");
if(strlen($subscribe) > 0) {
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcSubscribe" => $subscribe));
}
?>
<div class="page-title">
    <div class="title_left">
        <h3>User</h3>
    </div>
</div>
<?php if(isset($msg_result['status'])) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<?php if(isset($msg_delete['error']) && !empty($msg_delete['error'])) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-error alert-dismissible fade in" role="alert">
        <?php echo $msg_delete['error']; ?>
    </div>
<?php } ?>
<?php if(isset($msg_delete['success']) && !empty($msg_delete['success'])) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $msg_delete['success']; ?>
    </div>
<?php } ?>
    <div class="clearfix"></div>
    <form class="searchForm" name="form-user" method="post">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row " style="padding-bottom: 10px">
                        <div class="col-md-1">
                            <h2>Keyword</h2>
                        </div>
                        <div class="col-md-2">
                            <input class="form-control" type="text" name="txtSearch" maxlength="255" placeholder="ID, Name, Email" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                            <h2>From Date</h2>
                        <div class="col-md-2">
                            <input name="txtFrom" id="txtFrom" autocomplete="off" type="text" class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii' placeholder="From Date" value="<?php echo isset($from) ? $from : ''; ?>" >
                        </div>
                            <h2>To Date</h2>
                        <div class="col-md-2">
                            <input name="txtTo" id="txtTo" autocomplete="off" type="text" class="form-control datepicker-here" data-timepicker="true" data-time-format='hh:ii' placeholder="To Date" value="<?php echo isset($to) ? $to : ''; ?>" >
                        </div>

                    </div>
                    <div class="row ">
                        <div class="col-md-1">
                            <h2> Is Active</h2>
                        </div>
                        <div class="col-md-2">
                            <select class="form-control" name="slcActive" id="slcActive">
                                <option value="">Select All</option>
                                <option <?= $active == "Y" ? "selected" : ""?> value="Y">Yes</option>
                                <option <?= $active == "N" ? "selected" : ""?> value="N">No</option>
                            </select>
                        </div>
                        <h2 >Is Subscribe</h2>
                        <div class="col-md-2">
                            <select class="form-control" name="slcSubscribe" id="slcSubscribe">
                                <option value="">Select All</option>
                                <option <?= $subscribe == "Y" ? "selected" : ""?> value="Y">Yes</option>
                                <option <?= $subscribe == "N" ? "selected" : ""?> value="N">No</option>
                            </select>
                        </div>
                        <div class="col-md-2">
                            <button type="button" name="search" class="btn btn-success">Search</button>

                            <button type="submit" name="btnExportcsv" title="" class="btn btn-warning alignright">Export to CSV</button>
                        </div>

                    </div>
                    <div>
                        <strong>Total</strong>
                        <?= $total_record ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header">
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input type="checkbox" id="checkboxAll"><span class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID </th>
                                <th class="column-title">Name </th>
                                <th class="column-title">Email </th>
                                <th class="column-title">Role </th>
                                <th width="160px" class="column-title">Insert Time </th>
                                <th width="50px" class="column-title">Active </th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action </span></th>
                            </tr>
                            </thead>
                            <tbody class="tb_body">
                            <?php
                            foreach ($list_user as $item ) {
                                ?>
                                <tr>
                                    <td><label class="container_checkbox"><input class="check" name="item[]" value="<?php echo $item->user_id ?>" type="checkbox"><span class="checkmark_checkbox"></span></label></td>
                                    <td class=" ">#<?= $item->user_id ?></td>
                                    <td class=" "><?= $item->user_name ?></td>
                                    <td class=" "><?= $item->user_email ?></td>
                                    <td class=" "><?= $item->user_role ?></td>
                                     <td class=" "><?= $this->my->formatDateTime($item->user_insert_time) ?></td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->user_active;
                                        $classStatus = ($status == "Y") ? "success" : "danger" ;
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td class="last">
                                        <a class="btn btn-primary btn-xs margin-0" style="" href="<?php echo $this->url->get("/user/edit?id=".$item->user_id); ?>">View</a>
                                    </td>
                                </tr>

                            <?php }?>
                            </tbody>
                        </table>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-6 ">
                        <?php /*
                            <label for="slAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction" style="display: inline-block;width: 40%">
                                <option value="" selected >Please select</option>
                                <option value="drop">Drop</option>
                            </select>
 */ ?>
                    </div>
                    <div class="col-md-6 pull-right">
                        <?php if($total_page > 1) {?>
                            <nav class="paginate-footer">
                                <?php  if($urlPage != "?") $urlPage .= "&";
                                $urlPage .= "page=";
                                echo $this->my->renderPagination($urlPage, $current_page, $total_page, 2);
                                ?>
                            </nav>
                        <?php }?>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <button type="submit" name="btnExportcsvMKT" title="isMKT" class="btn btn-info alignright">Export CSV Email MKT</button>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </form>
    <script>
        $(document).ready(function(){
            $('button[name=search]').click(function() {
                $('form[name=form-user]').prop('action','<?php echo $this->url->get('/user'); ?>');
                $('form[name=form-user]').submit();
            });
            $('.delete-all').click(function(){
                $('form[name=form-user]').prop('action','<?php echo $this->url->get('/user/delete'); ?>');
                $('form[name=form-user]').submit();
            });
            $('button[name=btnExportcsv]').click(function() {
                $('form[name=form-user]').prop('action','<?php echo $this->url->get('/user/exportcsv'); ?>');
                $('form[name=form-user]').submit();
            });
            $('button[name=btnExportcsvMKT]').click(function() {
                $('form[name=form-user]').prop('action','<?php echo $this->url->get('/user/exportcsvmkt'); ?>');
                $('form[name=form-user]').submit();
            });
        });
    </script>

