<script>
    $(document).ready(function () {
        $('form[name=page-form]').submit(function (event) {
            var valid = true;

            if (!valid) event.preventDefault();
            if (valid) {
                $('button[name=sbmPage]').prop('disabled', true);
            }
        });


        $("#insertMulti").on('click', function () {
            var id = '<?= isset($formData['page_id']) ? $formData['page_id'] : 0 ?>';
            var tableName2 = 'visa_page';
            $.ajax({
                url: "<?php echo $this->url->get("/copydata/insertVN")?>",
                cache: false,
                type: "POST",
                dataType: "JSON",
                data: {
                    'id': id,
                    'tableName' : tableName2,
                },
                success: function (data) {
                    if (data.status) {
                        $('#insertMulti').hide();
                        $('#arlet').removeAttrs('hidden');
                        $('#arlet').html(data.messages);
                    } else {
                        $('#arlet').removeAttrs('hidden');
                        $('#arlet').html(data.messages);
                    }
                }
            });
        });
        $('.sbmUpdateContent').on("click", function (e) {
            var id = $(this).data('id');
            var country = $(this).data('country');
            var lang = $(this).data('lang');
            $.ajax({
                url: "<?= $this->url->get("/page/updatecontent")?>",
                method: "POST",
                data: {id: id ,country: country,lang:lang},
                success: function(response){
                    $('#arlet').text('Update Content Page success');
                    $('#arlet').removeClass('hidden');
                }
            });
        })
    });
</script>
<div class="page-title">
    <div class="title_left">
        <h3 class="type-title">Page</h3>

    </div>
</div>
<div class="clearfix"></div>

<?php if (!empty($messages['message'])) {
    ?>
    <p style="font-size:18px;text-align:center" class="alert alert-<?php echo $messages['typeMessage'] ?>">
        <?php echo $messages['message']; ?>
    </p>
<?php } ?>
<p style="font-size:18px;text-align:center" id="arlet"  class="alert alert-success hidden"></p>

<div id="loading" hidden
     style="position: fixed;z-index: 10000;top: 0px;left: 0px;width: 100%;height: 100%;background: #fff;filter: alpha(opacity=85);opacity: 1;background: rgba(255, 255,255,0);text-align: center; color:#f00;">
    <div style="background-color: #FDF7CC;border: 1px solid #FDC86C;border-radius: 4px;padding: 1px;margin: 20px auto;width: 50%;">
        <img src="<?php echo $this->url->getStatic('backend/img/waiting.gif'); ?>"
             alt='<?php echo htmlentities(defined('txt_processing') ? txt_processing : ''); ?>'
             title='<?php echo htmlentities(defined('txt_processing') ? txt_processing : ''); ?>'
             style="vertical-align:middle;position: relative;z-index: 10001;"/><?php echo defined('txt_processing') ? txt_processing : ''; ?>
        <span id="percent">0%</span>. Please waiting for the system to run!
    </div>
</div>
<div class="clearfix"></div>
<p id="alertInsertTranslate" hidden style="font-size:18px;text-align:center" class="alert alert-success">
    Update & Translate Page success
</p>
<p id="alertInsertTranslateError" hidden style="font-size:18px;text-align:center" class="alert alert-danger"></p>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Edit
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br/>
                <form name="page-form" id="page-form" data-parsley-validate class="form-horizontal form-label-left"
                      method="post">
                    <input type="hidden" name="save" id="save"
                           value="<?php echo \Indianimmigrationorg\Models\VisaLanguage::GENERAL; ?>"/>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Location Country <span
                                    class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select disabled class="form-control" name="slcLocationCountry" id="slcLocationCountry">
                                <?php
                                echo isset($select_location_country) ? $select_location_country : "";
                                ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Meta image </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input placeholder="1920 x 960"
                                   value="<?php echo isset($formData["page_meta_image"]) ? $formData["page_meta_image"] : "" ?>"
                                   id="txtMetaImage" name="txtMetaImage" class="form-control col-md-7 col-xs-12"
                                   type="text">
                        </div>
                    </div>
                     <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Is Landing Page </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radLanding" value="Y" <?php echo (isset($formData["page_is_landing_page"]) && $formData["page_is_landing_page"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radLanding" value="N" <?php echo (isset($formData["page_is_landing_page"]) && $formData["page_is_landing_page"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["page_active"]) && $formData["page_active"]=="Y" )  ? "checked" : '' ; ?>>Active<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["page_active"]) && $formData["page_active"]=="N" )  ? "checked" : '' ; ?>>InActive<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmPage" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary"
                               href="<?php echo $this->url->get("/page?slcLocationCountry=" . $location_country_code . "&slcLang=" . $formData['lang_current']); ?>">Cancel</a>
                            <?php
                            $contentArticleLang = \Indianimmigrationorg\Repositories\PageLang::findById($formData['page_id']);
                            if (count($contentArticleLang) == 0) {  ?>
                                <a id="insertMulti" class="btn btn-danger pull-right text-right">Insert VN/VI</a>
                            <?php } ?>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <ul class="nav nav-pills" role="tablist">
                <?php
                foreach ($formData['arr_language'] as $code => $lang) {
                    $active = $formData['lang_current'] == $code ? "active" : "";
                    ?>
                    <li role="presentation" class="<?php echo $active; ?>">
                        <a
                                href="#<?php echo $code ?>translate"
                                aria-controls="<?php echo $code ?>translate"
                                data-lang="<?= $code ?>"
                                class="tabLanguage"
                                role="tab"
                                data-toggle="tab"><?php echo strtoupper($code) . ' - '
                                . $lang;
                            ?></a></li>
                <?php } ?>
            </ul>
            <div class="tab-content">
                <?php foreach ($formData['arr_language'] as $code => $lang) {
                    $active = $formData['lang_current'] == $code ? "active" : "";
                    ?>
                    <div role="tabpanel" class="tab-pane <?php echo $active; ?>" id="<?php echo $code; ?>translate">
                        <br>
                        <form name="page-form<?php echo $code; ?>" id="page-form<?php echo $code; ?>" action=""
                              data-parsley-validate class="form-horizontal form-label-left" method="post">
                            <input type="hidden" name="save" id="save" value="<?php echo $code; ?>"/>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Name <span
                                            class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["page_name"]) ? $formData['arr_translate'][$code]["page_name"] : "" ?>"
                                           type="text" id="txtName<?php echo $code; ?>" name="txtName"
                                           class="form-control col-md-7 col-xs-12 <?php echo (isset($messages[$code]["name"])) ? $messages["status"] : ""; ?>">
                                    <span class="text-danger msg-name-<?php echo $code; ?>"><?php echo isset($messages[$code]["name"]) ? $messages[$code]["name"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Alias URL
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input  id="txtKeyword<?php echo $code; ?>"  name="txtKeyword"
                                            class="form-control <?php echo (isset($messages[$code]["page_keyword"])) ? $messages["status"] : ""; ?>"
                                            value="<?php echo isset($formData['arr_translate'][$code]["page_keyword"]) ? $formData['arr_translate'][$code]["page_keyword"] : "" ?>">
                                    <span class="text-danger msg-keyword-<?php echo $code; ?>"><?php echo isset($messages[$code]["page_keyword"]) ? $messages[$code]["page_keyword"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Title <span
                                            class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input maxlength="255"
                                           value="<?php echo isset($formData['arr_translate'][$code]["page_title"]) ? $formData['arr_translate'][$code]["page_title"] : "" ?>"
                                           type="text" id="txtTitle<?php echo $code; ?>" name="txtTitle"
                                           class="form-control col-md-7 col-xs-12 <?php echo (isset($messages[$code]["title"])) ? $messages["status"] : ""; ?>">
                                    <span class="text-danger msg-title-<?php echo $code; ?>"><?php echo isset($messages[$code]["title"]) ? $messages[$code]["title"] : ""; ?></span>
                                </div>
                            </div>


                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta keyword
                                    <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input  id="txtMetaKey<?php echo $code; ?>"  name="txtMetaKey"
                                           class="form-control <?php echo (isset($messages[$code]["meta_keyword"])) ? $messages["status"] : ""; ?>"
                                           value="<?php echo isset($formData['arr_translate'][$code]["page_meta_keyword"]) ? $formData['arr_translate'][$code]["page_meta_keyword"] : "" ?>">
                                    <span class="text-danger msg-metakeyword-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_keyword"]) ? $messages[$code]["meta_keyword"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Meta
                                    description <span class="text-danger">*</span>
                                </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <input  id="txtMetaDesc<?php echo $code; ?>"  name="txtMetaDesc"
                                              class="form-control <?php echo (isset($messages[$code]["meta_description"])) ? $messages["status"] : ""; ?>"
                                           value="<?php echo isset($formData['arr_translate'][$code]["page_meta_description"]) ? $formData['arr_translate'][$code]["page_meta_description"] : "" ?>">
                                    <span class="text-danger msg-metadescription-<?php echo $code; ?>"><?php echo isset($messages[$code]["meta_description"]) ? $messages[$code]["meta_description"] : ""; ?></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-md-3 col-sm-3 col-xs-12">Content </label>
                                <div class="col-md-6 col-sm-6 col-xs-12">
                                    <textarea id="txtContent<?php echo $code; ?>" class="form-control"  style=" height: 212px;"
                                              name="txtContent"><?php echo isset($formData['arr_translate'][$code]["page_content"]) ? $formData['arr_translate'][$code]["page_content"] : "" ?></textarea>
                                </div>
                            </div>

                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button name="sbmPage<?php echo $code; ?>" type="submit"
                                            class="btn btn-success"><?php echo 'Save (' . $lang.')'; ?></button>
                                    <?php /*
                                    <a data-country= "<?= $location_country_code ?>" data-lang="<?= $code; ?>" data-id= "<?= $formData['page_id']?>" id="sbmUpdateContent" class="btn btn-danger sbmUpdateContent">
                                        Update Field Lang (All field in table lang for all record Lang
                                        : <?= $lang ?>)
                                    </a>
  <?php */ ?>
                                </div>
                            </div>
                            <script>
                                $(document).ready(function () {
                                    $('#txtName<?php echo $code; ?>').on('input', function () {
                                        var id = <?php echo isset($formData['arr_translate'][$code]["page_id"]) ? $formData['arr_translate'][$code]["page_id"] : -1;?>;
                                        if (id < 0) {
                                            var str = $(this).val();
                                            var str_slug = slugify(str);
                                            $('#txtKeyword<?php echo $code; ?>').val(str_slug);
                                            $('#txtTitle<?php echo $code; ?>').val(str);
                                            $('#txtMetaKey<?php echo $code; ?>').val(str);
                                            $('#txtMetaDesc<?php echo $code; ?>').val(str);
                                        }
                                    });
                                    $('form[name=page-form<?php echo $code; ?>]').submit(function (event) {
                                        valid = true;
                                        if ($('#txtName<?php echo $code; ?>').val() == '') {
                                            valid = false;
                                            $('.msg-name-<?php echo $code;?>').text("Name field is required.");
                                            $('#txtName<?php echo $code; ?>').addClass("border-red");
                                        } else {
                                            $('.msg-name-<?php echo $code;?>').text('');
                                            $('#txtName<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtTitle<?php echo $code; ?>').val() == '') {
                                            $('.msg-title-<?php echo $code; ?>').text('Title field is required.');
                                            $('#txtTitle<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-title-<?php echo $code; ?>').text('');
                                            $('#txtTitle<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtKeyword<?php echo $code; ?>').val() == '') {
                                            $('.msg-keyword-<?php echo $code; ?>').text('Keyword field is required.');
                                            $('#txtKeyword<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-keyword-<?php echo $code; ?>').text('');
                                            $('#txtKeyword<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtMetaKey<?php echo $code; ?>').val() == '') {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('Meta keyword field is required.');
                                            $('#txtMetaKey<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metakeyword-<?php echo $code; ?>').text('');
                                            $('#txtMetaKey<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if ($('#txtMetaDesc<?php echo $code; ?>').val() == '') {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('Meta description field is required.');
                                            $('#txtMetaDesc<?php echo $code; ?>').addClass("border-red");
                                            valid = false;
                                        } else {
                                            $('.msg-metadescription-<?php echo $code; ?>').text('');
                                            $('#txtMetaDesc<?php echo $code; ?>').removeClass("border-red");
                                        }
                                        if (!valid) event.preventDefault();
                                        if (valid) {
                                            $('#sbmPage<?php echo $code; ?>').prop('disabled', true);
                                        }
                                    });
                                });
                            </script>
                        </form>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>