<?php
$urlPage = "?";
$location_country_code = isset($location_country_code) ? $location_country_code : '';
if (strlen($this->dispatcher->getParam("txtSearch")) > 0) {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
$slcLang = $this->dispatcher->getParam("slcLang");
if ($this->dispatcher->getParam("slcLang") != "") {
    if ($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcLang" => $slcLang));
}
if ($urlPage != "?") $urlPage .= "&";
$urlPage .= http_build_query(array("slcLocationCountry" => $location_country_code));

$radMatch = $this->dispatcher->getParam("radMatch");
if ($urlPage != "?") $urlPage .= "&";
$urlPage .= http_build_query(array("radMatch" => $radMatch));
?>
<div class="page-title">
    <div class="title_left">
        <h3>Page </h3>
    </div>
</div>
<?php if (isset($msg_result['status'])) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-<?php echo $msg_result['status'] ?> alert-dismissible fade in" role="alert">
        <?php echo $msg_result['msg']; ?>
    </div>
<?php } ?>
<?php if (isset($msg_delete['error']) && !empty($msg_delete['error'])) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-error alert-dismissible fade in" role="alert">
        <?php echo $msg_delete['error']; ?>
    </div>
<?php } ?>
<?php if (isset($msg_delete['success']) && !empty($msg_delete['success'])) { ?>
    <div class="clearfix"></div>
    <div class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $msg_delete['success']; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<div id="loading" hidden>
    <img class="lazyload padding-top10" src="<?php echo $this->url->getStatic('backend/'); ?>img/waiting.gif"
         style="vertical-align:middle;position: relative;z-index: 10001;"/> Processing...
</div>
<form class="searchForm" name="form-type" method="post">

    <?php
    $keyword = $this->dispatcher->getParam("txtSearch");
    $replace = $this->dispatcher->getParam("txtReplace");
    $area = $this->dispatcher->getParam("slcArea");
    ?>

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row form-group">
                        <div class="col-md-2">
                            <h2>Find</h2>
                        </div>
                        <div class="col-md-3">
                            <textarea class="form-control" type="text" name="txtSearch" id="txtSearch"
                                      placeholder="ID, Name, Content, Title, Meta Keyword, Meta Description"><?php echo isset($keyword) ? $keyword : ''; ?></textarea>
                            <span class="text-danger msg-search" style="color: #a94442 !important;"></span>
                        </div>
                        <div class="col-md-1">
                            <h2 class="">Replace</h2>
                        </div>
                        <div class="col-md-3">
                            <textarea class="form-control" type="text" name="txtReplace"
                                      placeholder="Name, Content, Title, Meta Keyword, Meta Description"><?php echo isset($replace) ? $replace : ''; ?></textarea>
                        </div>
                    </div>
                    <div class="row" style="margin-top: 15px">
                        <div class="col-md-2">
                            <h2>Location Country</h2>
                        </div>
                        <div class="col-md-3">
                            <select class="form-control" name="slcLocationCountry" id="slcLocationCountry">
                                <?php
                                echo isset($select_location_country) ? $select_location_country : "";
                                ?>
                            </select>
                        </div>
                        <div class="col-md-1">
                            <h2 class="">Language</h2>
                        </div>
                        <div class="col-md-2">
                            <select class="form-control" name="slcLang" id="slcLang">

                            </select>
                        </div>
                        <div class="col-md-4 pull-right" style="display: flex">
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="radMatch" id="radMatch"
                                       value="match" <?php echo ($radMatch == 'match') ? 'checked' : ''; ?>>
                                <label class="form-check-label" for="radMatch">
                                    Match
                                </label>
                            </div>
                            <div class="form-check" style="margin-left: 10px;margin-right: 10px">
                                <input class="form-check-input" type="radio" name="radMatch" id="notMatch"
                                       value="notmatch" <?php echo ($radMatch == 'notmatch') ? 'checked' : ''; ?>>
                                <label class="form-check-label" for="notMatch">
                                    Not match
                                </label>
                            </div>
                            <button type="button" name="search" class="btn btn-success ">Search</button>
                            <input type="hidden" name="checkbtnReplace" value="FALSE"/>
                            <button type="button" name="btnReplace" class="btn btn-danger"
                                    style="margin-left: 20px;margin-right: 20px" id="btnReplace">Replace
                            </button>
                            <a class="btn btn-info"
                               href="<?php echo $this->url->get("/page/create"); ?>">Add
                                New</a>
                        </div>
                    </div>
                    <div>
                        <strong>Total</strong>
                        <?php echo $page->total_items ?> records
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header">
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input
                                                type="checkbox" id="checkboxAll"><span
                                                class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID</th>
                                <th class="column-title">Name</th>
                                <th class="column-title">Location Country</th>
                                <th class="column-title">Language</th>
                                <th class="column-title">Title</th>
                                <th width="50px" class="column-title">Status</th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>

                            <tbody class="tb_body">
                            <?php foreach ($page->items as $item) { ?>

                                <?php
                                /**
                                 * @var \Indianimmigrationorg\Models\VisaPage $item
                                 */
                                ?>
                                <tr>
                                    <td>
                                        <label class="container_checkbox">
                                            <input class="check" name="item[]"
                                                   id="type-checkbox<?php echo $item->getPageId(); ?>"
                                                   value="<?php echo $item->getPageId(); ?>" type="checkbox">
                                            <span class="checkmark_checkbox"></span>
                                        </label>
                                    </td>
                                    <td class=" "><?php echo $item->getPageId(); ?></td>
                                    <td class=" "><?php echo $item->getPageName(); ?></td>
                                    <td class=" "><?php echo \Indianimmigrationorg\Repositories\CountryGeneral::getCountryNameOrGlobalByCode($item->getPageLocationCountryCode()); ?></td>
                                    <td class=" ">
                                        <?php echo \Indianimmigrationorg\Repositories\Language::getNameByCode($slcLang); ?></td>
                                    <td class=" "><?php echo $item->getPageTitle(); ?></td>
                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getPageActive();
                                        $classStatus = ($status == "Y") ? "success" : "danger";
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td class="last">
                                        <a class="btn btn-primary btn-xs margin-0" style=""
                                           href="<?php echo $this->url->get("/page/edit?id=" . $item->getPageId() . "&slcLocationCountry=" . strtoupper($item->getPageLocationCountryCode()) . "&slcLang=" . $slcLang); ?>">View</a>
                                    </td>
                                </tr>
                            <?php } ?>
                            </tbody>
                        </table>

                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <label for="slcAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction"
                                    style="display: inline-block;width: 40%">
                                <option value="" selected>Please select</option>
                                <option value="drop">Drop</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <?php if ($page->total_pages > 1) { ?>
                                <nav class="paginate-footer">
                                    <?php if ($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $page->current, $page->total_pages, 2);
                                    ?>
                                </nav>
                            <?php } ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</form>
<script>
    $(document).ready(function () {
        $('button[name=search]').click(function () {
            $('form[name=form-type]').prop('action', '<?php echo $this->url->get('/page'); ?>');
            $('form[name=form-type]').submit();
        });

        $('.delete-all').click(function () {
            $('form[name=form-type]').prop('action', '<?php echo $this->url->get('/page/delete'); ?>');
            $('form[name=form-type]').submit();
        });

        $('button[name=btnReplace]').click(function () {
            if (confirm('Are you sure you want to Replace?')) {
                $('#loading').show();
                $('input[name=checkbtnReplace]').val('TRUE');
                $('form[name=form-type]').prop('action', '<?php echo $this->url->get('/page'); ?>');
                $('form[name=form-type]').submit();
                $('button[name=search]').prop('disabled', true);
                $('button[name=btnReplace]').prop('disabled', true);
            }
        });

        $('#txtSearch').blur(function () {
            var country_code = $("#slcLocationCountry option:selected").val();
            if ($(this).val().trim().split(" ").length < 2 && $(this).val().trim().length < 1 && country_code === 'all') {
                $('.msg-search').text('Keyword needs to be greater than 2 words');
            } else {
                $('.msg-search').text('');
            }
        });

        $("#slcLocationCountry").change(function () {
            var country_code = $("#slcLocationCountry option:selected").val();
            if (country_code === 'all') {
                if ($('#txtSearch').val().trim().split(" ").length < 2 && $('#txtSearch').val().trim().length < 1) {
                    $('.msg-search').text('Keyword needs to be greater than 2 words');
                }
            } else {
                $('.msg-search').text('');
            }
            var lang_code = '<?php echo $slcLang; ?>';
            $.ajax({
                url: "<?php echo $this->url->get('/location/getlangbycode'); ?>",
                type: 'POST',
                data: {country_code: country_code, lang_code: lang_code},
                success: function (data) {
                    var getData = JSON.parse(data);
                    $("#slcLang").html('');
                    $("#slcLang").append(getData.string_json);
                }
            });
        }).trigger('change');
    });
</script>