<script>
    $( document ).ready(function() {
        $('form[name=banner-form]').submit(function(event) {
            var valid = true;
            if($( "select#slcController option:checked" ).val()==0) {
                $('.msg-controller').text('Controller is required.');
                $('#slcController').addClass("border-red");
                valid = false;
            } else {
                $('.msg-controller').text('');
                $('#slcController').removeClass("border-red");
            }
            if($('input[name=txtImage]').val() == '') {
                $('.msg-img').text('Image field is required.');
                $('#txtImage').addClass("border-red");
                valid = false;
            } else {
                $('.msg-img').text('');
                $('#txtImage').removeClass("border-red");
            }
            if($('input[name=txtImageMobile]').val() == '') {
                $('.msg-img-mobile').text('Image Mobile field is required.');
                $('#txtImageMobile').addClass("border-red");
                valid = false;
            } else {
                $('.msg-img-mobile').text('');
                $('#txtImageMobile').removeClass("border-red");
            }
            if($('input[name=txtName]').val() == '') {
                $('.msg-name').text('Name field is required.');
                $('#txtName').addClass("border-red");
                valid = false;
            } else {
                $('.msg-name').text('');
                $('#txtName').removeClass("border-red");
            }
            if($('input[name=txtOrder]').val() == '') {
                $('.msg-order').text('Order field is required.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else if (isNaN($('input[name=txtOrder]').val())) {
                $('.msg-order').text('Enter a valid order.');
                $('#txtOrder').addClass("border-red");
                valid = false;
            } else {
                $('.msg-order').text('');
                $('#txtOrder').removeClass("border-red");
            }
            if( ! valid ) event.preventDefault();
            if( valid ) {
                $('button[name=sbmBanner]').prop('disabled', true);
            }
        });
    });
</script>

<div class="page-name">
    <div class="title_left">
        <h3 class="banner-name">Banner </h3>
    </div>
</div>
<div class="clearfix"></div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_title">Form Create</div>
            <div class="x_content">
                <br />
                <form name="banner-form" id="banner-form" action="<?php echo $this->url->get('/banner/create'); ?>" data-parsley-validate class="form-horizontal form-label-left" method="post">
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">Controller <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <select id="slcController" name="slcController" class="form-control col-md-7 col-xs-12  <?php echo (isset($messages["controller"])) ? $messages["status"] : ""; ?>" >
                                <option value="">Select Controller...</option>
                                <?php echo isset($select_controller)? $select_controller : ''?>
                            </select>
                            <span class="text-danger msg-controller"><?php echo isset($messages["controller"]) ? $messages["controller"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Image <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_image"]) ? $formData["banner_image"] : "" ?>" type="text" id="txtImage" name="txtImage"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["image"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-img"><?php echo isset($messages["image"]) ? $messages["image"] : "";?></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Image Mobile <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_image_mobile"]) ? $formData["banner_image_mobile"] : "" ?>" type="text" id="txtImageMobile" name="txtImageMobile" class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["image_mobile"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-img-mobile"><?php echo isset($messages["image_mobile"]) ? $messages["image_mobile"] : "";?></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Name  <span class="text-danger">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_name"]) ? $formData["banner_name"] : "" ?>" type="text" id="txtName" name="txtName"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["name"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-name"><?php echo isset($messages["name"]) ? $messages["name"] : ""; ?></span>
                        </div>
                    </div>



                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Content </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <textarea class="form-control" id="txtContent" name ="txtContent" style="height: 112px;" ><?php echo isset($formData["banner_content"]) ? $formData["banner_content"] : "" ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Link</label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="255" value="<?php echo isset($formData["banner_link"]) ? $formData["banner_link"] : "" ?>" type="text" id="txtLink" name="txtLink"   class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["link"])  ) ? $messages["status"] : ""; ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Order <span class="text-danger">*</span>
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input maxlength="10" value="<?php echo isset($formData["banner_order"]) ? $formData["banner_order"] : "" ?>" type="text" id="txtOrder" name="txtOrder"  class="form-control col-md-7 col-xs-12 <?php echo (isset($messages["order"])) ? $messages["status"] : ""; ?>">
                            <span class="text-danger msg-order"><?php echo isset($messages["order"]) ? $messages["order"] : "";?></span>
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Active </label>
                        <div class="col-md-6 col-sm-6 col-xs-12 form-check">
                            <label class="container_radio"><input type="radio" name="radActive" value="Y" <?php echo (isset($formData["banner_active"]) && $formData["banner_active"]=="Y" )  ? "checked" : '' ; ?>>Yes<span class="checkmark"></span></label>
                            <label class="container_radio"><input type="radio" name="radActive" value="N" <?php echo (isset($formData["banner_active"]) && $formData["banner_active"]=="N" )  ? "checked" : '' ; ?>>No<span class="checkmark"></span></label>
                        </div>
                    </div>
                    <div class="ln_solid"></div>
                    <div class="form-group">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button name="sbmBanner" type="submit" class="btn btn-success">Save change</button>
                            <a class="btn btn-primary" href="/banner">Cancel</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
