<?php
$urlPage = "?";
if(strlen($this->dispatcher->getParam("txtSearch"))> 0){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("txtSearch" => $this->dispatcher->getParam("txtSearch")));
}
if($this->dispatcher->getParam("slcController") != ""){
    if($urlPage != "?") $urlPage .= "&";
    $urlPage .= http_build_query(array("slcController" => $this->dispatcher->getParam("slcController")));
}

?>
<div class="page-title">
    <div class="title_left">
        <h3>Banner </h3>
    </div>
</div>
<?php if(isset($msg_result))  {?>
<div class="clearfix"></div>
<div  class="alert alert-<?php echo $msg_result['status']?> alert-dismissible fade in" role="alert">
    <?php echo $msg_result['msg']; ?>
</div>
<?php } ?>
<?php $message_success = isset($msg_del["success"])? $msg_del["success"] :'';
$message_error = isset($msg_del["error"])? $msg_del["error"] :'';
if(!empty($message_success)) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-success alert-dismissible fade in" role="alert">
        <?php echo $message_success; ?>
    </div>
<?php }if(!empty($message_error)) { ?>
    <div class="clearfix"></div>
    <div  class="alert alert-error alert-dismissible fade in" role="alert">
        <?php echo $message_error; ?>
    </div>
<?php } ?>
<div class="clearfix"></div>
<form class="searchForm" name="form-banner" method="post" action="">

    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_title">
                    <div class="row ">
                            <h2 class="">Keyword</h2>
                        <div class="col-md-3">
                            <input maxlength="255" class="form-control" type="text" name="txtSearch" placeholder="ID, Name" value="<?php echo isset($keyword) ? $keyword : ""; ?>">
                        </div>
                        <h2 class="align-center">Controller</h2>
                        <div class="col-md-2">
                            <select class="form-control" name="slcController" id="slcController">
                                <option value="0">All Controller</option>
                                <?php echo isset($select_controller)? $select_controller : '' ?>
                            </select>
                        </div>
                        <div class="col-md-2 ">
                            <button type="button" name="search" class="btn btn-success">Search</button>
                            <a class="btn btn-info" href="<?php echo $this->url->get("/banner/create"); ?>">Add New</a>
                        </div>

                    </div>
                    <div >
                        <strong>Total</strong>
                        <?php echo $list_banner->total_items ?> records
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="x_content">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="table_header" >
                            <tr class="headings">
                                <th style="text-align: left" width="50px"><label class="container_checkbox"><input type="checkbox" id="checkboxAll"><span class="checkmark_checkbox"></span></label></th>
                                <th width="50px" class="column-title">ID </th>
                                <th class="column-title">Name </th>
                                <th class="column-title">Controller </th>
                                <th width="50px" class="column-title">Order </th>
                                <th width="50px" class="column-title">Active </th>
                                <th width="50px" class="column-title no-link last"><span class="nobr">Action</span></th>
                            </tr>
                            </thead>

                            <tbody class="tb_body">
                            <?php

                            foreach ($list_banner->items as $item) {
                                $controller ='';
                                $type = '';
                                $article = '';
                                if(!empty($item->getBannerController())) {
                                    $controller = \Indianimmigrationorg\Repositories\Banner::CONTROLLER.'_'.$item->getBannerController();
                                }
                                $name = \Indianimmigrationorg\Repositories\Banner::getNameController($controller,$article);
                                ?>
                                <tr >
                                    <td>
                                        <label class="container_checkbox">
                                            <input class="check" name="item[]" type="checkbox"
                                                   value="<?php echo $item->getBannerId(); ?>">
                                            <span class="checkmark_checkbox">
                                            </span>
                                        </label>
                                    </td>
                                    <td class=" "><?php echo $item->getBannerId(); ?></td>
                                    <td class=" "><?php echo $item->getBannerName() ?></td>
                                    <td class=" "><?php echo $name; ?></td>
                                    <td class=" "><?php echo $item->getBannerOrder() ?></td>

                                    <td class="text-center" data-title="Active">
                                        <?php
                                        $status = $item->getBannerActive();
                                        $classStatus = ($status == "Y") ? "success" : "danger" ;
                                        ?>
                                        <span class="label label-<?php echo $classStatus; ?>"><?php echo $status; ?></span>
                                    </td>
                                    <td><a class="btn btn-primary btn-xs margin-0"   href="<?php echo $this->url->get("/banner/edit?id=".$item->getBannerId()); ?> ">View</a>
                                    </td>
                                </tr>

                            <?php }?>
                            </tbody>
                        </table>

                    </div>
                    <div class="clearfix"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <label for="slAction">With Selected:</label>
                            <select class="form-control" id="slcAction" name="slcAction" style="display: inline-block;width: 40%">
                                <option value="" selected >Please select</option>
                                <option value="drop">Drop</option>
                            </select>
                        </div>
                        <div class="col-md-6">
                            <?php if($list_banner->total_pages > 1) {?>
                                <nav class="paginate-footer">
                                    <?php  if($urlPage != "?") $urlPage .= "&";
                                    $urlPage .= "page=";
                                    echo $this->my->renderPagination($urlPage, $list_banner->current, $list_banner->total_pages,2);
                                    ?>
                                </nav>
                            <?php }?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    $(document).ready(function(){
        $('button[name=search]').click(function() {
            $('form[name=form-banner]').prop('action','<?php echo $this->url->get('/banner'); ?>');
            $('form[name=form-banner]').submit();
        });

        $('.delete-all').click(function(){
            $('form[name=form-banner]').prop('action','<?php echo $this->url->get('/banner/delete'); ?>');
            $('form[name=form-banner]').submit();
        });
    });
</script>